FROM open-liberty:springBoot2-java11

ARG image_name
ARG image_version

RUN echo "image variables $image_name $image_version"

COPY --chown=1001:0 ./build/libs/${image_name}-${image_version}.war /config/dropins/

EXPOSE 9080 9443